### ISSUE TITLE
unsupported

### ISSUE THREAD

**Issue by dmpx** [dvhb/badbrowser#5]
unsupported: {
    mobile: false
 }

mobile is Invalid

**Comment by alexbee** [comment]
@dmpx 

option `unsupported: { mobile: true }` show alert for any mobile browser
option `unsupported: { mobile: false }` will not show alert for mobile browser (it's alternative for `supported: { mobile: true }`)

Check new tests. 
https://github.com/dvhbru/badbrowser/blob/master/test/badbrowser.test.js#L166-L178
https://travis-ci.org/dvhbru/badbrowser/jobs/326393525#L526

If you are sure that there is an error, please show a code sample demonstrating bug
